language: python
sudo: false
python:
- '2.6'
- '2.7'
- '3.3'
env:
- DJANGO=1.4.2
- DJANGO=1.5.1
- DJANGO=1.6.0
- DJANGO=1.7.0
- DJANGO=1.8.0
matrix:
  exclude:
  - python: '3.3'
    env: DJANGO=1.4.2
  - python: '2.6'
    env: DJANGO=1.7.0
  - python: '2.6'
    env: DJANGO=1.8.0
before_install:
- pip install codecov
install:
- pip install Django==$DJANGO -e .
script:
- coverage run --source=any_urlfield runtests.py
after_script:
- codecov
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: V+skNUEC7EyI29t5H7zO+CmY9uRqbQHoRyj12VPN057ayQUaXAX/mh5pYqwyiTYdywfwo0/7ruPMZtyKHN+dE1MKvXu2F7QMb83Fk1pJ+lSeti+IV6XwlaZYnvTR3KoWublrHRl/VxbbBdYlGEU2zr612vO1nRvC6Zb6cFprscw=
    on_success: never
    on_failure: always
