sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.4'
env:
- PACKAGES="django>=1.7.0,<1.8.0"
- PACKAGES="django>=1.8.0,<1.9.0"
- PACKAGES="django>=1.9.0,<1.10.0"
- PACKAGES="django>=1.10.0,<1.11.0"
- PACKAGES="django>=1.11.0,<1.12.0"
before_install:
- pip install codecov
install:
- pip install -U pip wheel
- travis_retry pip install $PACKAGES -e .
script:
- coverage run --source=any_urlfield runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: V+skNUEC7EyI29t5H7zO+CmY9uRqbQHoRyj12VPN057ayQUaXAX/mh5pYqwyiTYdywfwo0/7ruPMZtyKHN+dE1MKvXu2F7QMb83Fk1pJ+lSeti+IV6XwlaZYnvTR3KoWublrHRl/VxbbBdYlGEU2zr612vO1nRvC6Zb6cFprscw=
    on_success: never
    on_failure: always
